### ISSUE TITLE
The purpose of Pulsar

### ISSUE THREAD

**Issue by HelloTo4x** [aploetz/avroStreamExample#1]
Hi, i am reading your project, why don't u use Kafka or RabbitMQ as message queue instead of Pulsar, can you tell me why you choose Pulsar, do you know the pros and cons of Pulsar, if yes, can tell me, thank u so much

**Comment by aploetz** [comment]
@HelloTo4x  I work for DataStax, and Apache Pulsar is one of the products we support.  I've built out a couple of repos for that (like this one) around helping some of our customers and folks in the OSS community solve problems with Pulsar.

There are a lot of sites out there touting Pulsar over Kafka, or vice-versa, but really, it's all marketing.  One of the true advantages of Pulsar over Kafka or RabbitMQ, is that it tends to scale better.  Likewise, Pulsar can be set up to run in a distributed, multi-datacenter paradigm, while other messaging/pub-sub platforms will have issues with multiple DCs or cloud regions.

But that all being said, Pulsar is also super easy to use and get started with.

**Comment by HelloTo4x** [comment]
Thank u, I know Datasax, but can you explain to me in more detail or give me a link about "run in a distributed",  "scale better", "other messaging/pub-sub platforms will have issues with multiple DCs or cloud regions" ?
